language: php

php:
  - 7.2
  - 7.3
  - 7.4

os: linux

before_script:
  - composer self-update
  - composer install --dev --no-interaction --prefer-source

notifications:
  email:
    - "jon@jon.se"
